object Dependencies {
    val path_gradle = "com.android.tools.build:gradle:${Versions.gradle}"
    val path_gradle_kotlin = "org.jetbrains.kotlin:kotlin-gradle-plugin:${Versions.kotlin}"
    val kotlin_core_ktx = "androidx.core:core-ktx:${Versions.koreKtx}"
    val kotlin_stdlib_jdk = "org.jetbrains.kotlin:kotlin-stdlib-jdk8:${Versions.kotlin}"
    val dagger = "com.google.dagger:dagger:${Versions.dagger}"
    val dagger_compiler = "com.google.dagger:dagger-compiler:${Versions.dagger}"
    val dagger_android = "com.google.dagger:dagger-android:${Versions.dagger}"
    val dagger_android_support = "com.google.dagger:dagger-android-support:${Versions.dagger}"
    val dagger_android_compiler = "com.google.dagger:dagger-android-processor:${Versions.dagger}"
    val android_multiDex = "com.android.support:multidex:${Versions.multiDex}"
    val android_appcompat = "androidx.appcompat:appcompat:${Versions.appcompat}"
    val android_legacy_support = "androidx.legacy:legacy-support-v4:${Versions.legacy_support}"
    val android_constraint_layout = "androidx.constraintlayout:constraintlayout:${Versions.constraintLayoutVersion}"
    val retrofit_gson = "com.squareup.retrofit2:converter-gson:${Versions.retrofit}"
    val retrofit = "com.squareup.retrofit2:retrofit:${Versions.retrofit}"
    val okhttp3_nterceptor = "com.squareup.okhttp3:logging-interceptor:${Versions.okhttp3}"
    val okhttp3 = "com.squareup.okhttp3:okhttp:${Versions.okhttp3}"
    val parse_sdk = "com.github.parse-community.Parse-SDK-Android:parse:${Versions.parseSDK}"
    val parse_facebook_sdk = "com.github.parse-community:ParseFacebookUtils-Android:${Versions.parseFacebookSDK}"
    val facebook_sdk = "com.facebook.android:facebook-android-sdk:${Versions.facebookSDK}"
    val glide = ("com.github.bumptech.glide:glide:4.9.0")
    val material_design_new = "com.google.android.material:material:${Versions.materialDesignNew}"
    val viewmodel_extension = "androidx.lifecycle:lifecycle-extensions:${Versions.viewModelVersion}"
    val frag_nav_ctrl = "com.ncapdevi:frag-nav:${Versions.fragNavCtrlVersion}"
}
