package app.apirequest.parse

object Property {
    const val FILE = "file"
    const val FILE_NAME = "filename"
    const val USER = "user"
    const val ACCOUNT_TYPE = "accountType"
    const val HAS_PRIVATE_TUTORING = "hasPrivateTutoring"
    const val GENDER = "gender"
    const val DEGREE = "degree"
    const val PROGRAM_OF_STUDY = "programOfStudy"
    const val IMAGE = "image"
    const val SPECIALIZATION = "specialization"
    const val SUBJECTS_TAUGHT = "subjectsTaught"
    const val PT_SEEKS_TO_LEARN = "ptSeeksToLearn"
    const val PT_TUITION_TYPE = "ptTuitionType"
    const val PT_CURRENCY = "ptCurrency"
    const val PT_FEES_PER_HOUR = "ptFeesPerHour"
    const val PT_TEACHING_MODE = "ptTeachingMode"
    const val PT_YEARS_OF_EXPERIENCE = "ptYearsOfExperience"
    const val PT_TUTORING_EXPERIENCE = "ptTutoringExperience"
    const val INSTITUTION_DESCRIPTION = "institutionDescription"
    const val INSTITUTION_TYPE = "institutionType"
    const val INSTITUTION_IMAGE1 = "institutionImage1"
    const val FULL_NAME = "fullname"
    const val CONTACT_NUMBER = "contactNumber"
    const val COUNTRY = "country"
    const val CITY = "city"
    const val IS_SIGN_UP_COMPLETED = "isSignupCompleted"
    const val IS_ACTIVE = "isActive"
    const val HAS_CITY = "hasCity"
    const val SOCIAL_LOGIN_EMAIL = ""
    const val SOCIAL_LOGIN_ID = "socialLoginId"
    const val EMAIL_MASTER_PERMISSION = "emailMasterPermission"
    const val VIDEO_CALL_MASTER_PERMISSION = "videoCallMasterPermission"
    const val AUDIO_CALL_MASTER_PERMISSION = "audioCallMasterPermission"
    const val CHAT_MASTER_PERMISSION = "chatMasterPermission"
}